"""Add search vectors

Revision ID: cae099d021e3
Revises: 78663177b0be
Create Date: 2026-08-12 17:16:28.881054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cae099d021e3'
down_revision: Union[str, Sequence[str], None] = '78663177b0be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', content)", ), nullable=False))
    op.create_index('ix_comments_search', 'comments', ['search_vector'], unique=False, postgresql_using='gin')
    op.add_column('projects', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('projects', sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('projects', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', name || ' ' || coalesce(description, ''))", ), nullable=False))
    op.create_index('ix_projects_search', 'projects', ['search_vector'], unique=False, postgresql_using='gin')
    op.add_column('tasks', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', title || ' ' || coalesce(description, ''))", ), nullable=False))
    op.drop_index(op.f('ix_tasks_fts'), table_name='tasks', postgresql_using='gin')
    op.create_index('ix_tasks_search', 'tasks', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_search', table_name='tasks', postgresql_using='gin')
    op.create_index(op.f('ix_tasks_fts'), 'tasks', [sa.literal_column("to_tsvector('english'::regconfig, (title::text || ' '::text) || COALESCE(description, ''::text))")], unique=False, postgresql_using='gin')
    op.drop_column('tasks', 'search_vector')
    op.drop_index('ix_projects_search', table_name='projects', postgresql_using='gin')
    op.drop_column('projects', 'search_vector')
    op.drop_column('projects', 'is_public')
    op.drop_column('projects', 'is_active')
    op.drop_index('ix_comments_search', table_name='comments', postgresql_using='gin')
    op.drop_column('comments', 'search_vector')
    # ### end Alembic commands ###
